import { Schema, model, models, type Document, type Model } from 'mongoose';
import type { SetupType, SwingStatus } from '@/lib/swing/types';
import type { TrendDirection } from '@/lib/technical/trend';
import type { DailyChangeClassification } from '@/lib/analysis/dailyChangeClassification';

/**
 * One instrument's swing-analysis result for one completed market session —
 * generated by reusing the existing deterministic Swing Engine (see
 * lib/analysis/dailySnapshotService.ts), never a second scoring
 * implementation. Distinct from Candidate (database/models/candidate.model.ts):
 * a Candidate is a user's deliberate, immutable "I saved this" moment, while
 * a DailyAnalysisSnapshot is an OBJECTIVE, market-wide, unattended daily
 * observation — every tracked instrument gets one every session whether or
 * not any user ever looks at it, and it is never mutated once written for a
 * given (symbol, market, marketDate, strategyVersion) except by a deliberate
 * regeneration (an upsert of the SAME key). Saving a Candidate must never
 * write to or depend on this collection — see docs/daily-data-engine.md.
 *
 * No TTL: like MarketBar, these are small and are the raw material for the
 * weekly review's multi-day history, so they are kept permanently.
 */
export interface DailyAnalysisSnapshotDocument extends Document {
    symbol: string;
    market: string;
    exchange?: string;
    currency?: string;

    /** YYYY-MM-DD — the actual market session this observation reflects
     * (the latest bar's own date), NEVER "today" by wall-clock assumption.
     * A symbol whose local data is stale gets a snapshot dated by whatever
     * session its data actually covers, not backdated or fabricated to
     * match today (see docs/daily-data-engine.md's "market session
     * awareness"). */
    marketDate: string;
    close: number;

    score: number;
    maxScore: number;
    status: SwingStatus;
    setupType?: SetupType;
    rsi: number | null;
    relativeVolume: number | null;
    trend: TrendDirection;

    /** Which strategy config produced this — see lib/swing/configFingerprint.ts.
     * Part of the uniqueness key so a strategy-config edit never silently
     * overwrites (or gets compared against) a snapshot produced by a
     * different config. */
    strategyVersion: string;

    /** Comparison against the most recent PRIOR snapshot for the same
     * (symbol, market, strategyVersion) — computed once at generation time
     * (see lib/analysis/dailyChangeClassification.ts) so every reader sees
     * the same classification rather than each recomputing it. Never a
     * buy/sell instruction — purely descriptive. */
    changeClassification: DailyChangeClassification;
    /** current.score - previous.score; null when there was no prior
     * snapshot to compare against (this instrument's first observation). */
    scoreChange: number | null;

    calculatedAt: Date;
}

const DailyAnalysisSnapshotSchema = new Schema<DailyAnalysisSnapshotDocument>({
    symbol: { type: String, required: true, uppercase: true, trim: true },
    market: { type: String, required: true },
    exchange: { type: String },
    currency: { type: String },

    marketDate: { type: String, required: true },
    close: { type: Number, required: true },

    score: { type: Number, required: true },
    maxScore: { type: Number, required: true },
    status: { type: String, enum: ['PASS', 'WATCH', 'QUALIFIED'], required: true },
    setupType: { type: String },
    rsi: { type: Number, default: null },
    relativeVolume: { type: Number, default: null },
    trend: { type: String, required: true },

    strategyVersion: { type: String, required: true },

    changeClassification: { type: String, required: true },
    scoreChange: { type: Number, default: null },

    calculatedAt: { type: Date, required: true, default: Date.now },
});

// Uniquely identifies one observation (so a regeneration for the same
// session safely overwrites via upsert rather than duplicating — same
// pattern as MarketBar's unique index) and, scanned in either direction,
// serves both "today's full snapshot for a market" and "one symbol's score
// history over its last N sessions" queries.
DailyAnalysisSnapshotSchema.index({ symbol: 1, market: 1, strategyVersion: 1, marketDate: 1 }, { unique: true });
// "Every symbol's snapshot for market X on session Y" — the Daily Review
// dashboard's primary query (see docs/scanner.md).
DailyAnalysisSnapshotSchema.index({ market: 1, marketDate: 1 });

export const DailyAnalysisSnapshot: Model<DailyAnalysisSnapshotDocument> =
    (models?.DailyAnalysisSnapshot as Model<DailyAnalysisSnapshotDocument>) ||
    model<DailyAnalysisSnapshotDocument>('DailyAnalysisSnapshot', DailyAnalysisSnapshotSchema);
